"""initial_schema

Revision ID: 35e7b29c0008
Revises: 
Create Date: 2026-04-09 12:40:32.311172
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35e7b29c0008'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_type', sa.String(length=50), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('arch', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('api_key_hash', sa.Text(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_device_id'), 'alerts', ['device_id'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_device_id'), 'commands', ['device_id'], unique=False)
    op.create_table('device_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('ram_percent', sa.Float(), nullable=True),
    sa.Column('disk_percent', sa.Float(), nullable=True),
    sa.Column('cpu_temp', sa.Float(), nullable=True),
    sa.Column('uptime_secs', sa.BigInteger(), nullable=True),
    sa.Column('ram_total_mb', sa.Float(), nullable=True),
    sa.Column('ram_used_mb', sa.Float(), nullable=True),
    sa.Column('disk_total_gb', sa.Float(), nullable=True),
    sa.Column('disk_used_gb', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_metrics_device_id'), 'device_metrics', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_metrics_time'), 'device_metrics', ['time'], unique=False)
    op.create_table('device_network_info',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('interface_name', sa.String(length=255), nullable=False),
    sa.Column('mac_address', sa.String(length=64), nullable=True),
    sa.Column('ipv4', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('ipv6', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_up', sa.Boolean(), nullable=False),
    sa.Column('mtu', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_network_info_device_id'), 'device_network_info', ['device_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_device_id'), 'events', ['device_id'], unique=False)
    op.create_index(op.f('ix_events_time'), 'events', ['time'], unique=False)
    op.create_table('software_inventory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('update_available', sa.Boolean(), nullable=False),
    sa.Column('latest_version', sa.String(length=100), nullable=True),
    sa.Column('last_scanned', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_software_inventory_device_id'), 'software_inventory', ['device_id'], unique=False)
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'timescaledb') THEN
                PERFORM create_hypertable('device_metrics', 'time', if_not_exists => TRUE);
            END IF;
        EXCEPTION
            WHEN undefined_function THEN
                NULL;
            WHEN OTHERS THEN
                NULL;
        END$$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_software_inventory_device_id'), table_name='software_inventory')
    op.drop_table('software_inventory')
    op.drop_index(op.f('ix_events_time'), table_name='events')
    op.drop_index(op.f('ix_events_device_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_device_network_info_device_id'), table_name='device_network_info')
    op.drop_table('device_network_info')
    op.drop_index(op.f('ix_device_metrics_time'), table_name='device_metrics')
    op.drop_index(op.f('ix_device_metrics_device_id'), table_name='device_metrics')
    op.drop_table('device_metrics')
    op.drop_index(op.f('ix_commands_device_id'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_alerts_device_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('devices')
    # ### end Alembic commands ###
